language: scala
scala:
  - 2.11.7
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
jdk:
  - oraclejdk8
notifications:
  email:
    - fedeoasi+ljp@gmail.com
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/