create table "USERS" ("PROVIDER_ID" VARCHAR(254) NOT NULL,"USER_ID" VARCHAR(254) NOT NULL,"FIRST_NAME" VARCHAR(254),"LAST_NAME" VARCHAR(254),"FULL_NAME" VARCHAR(254),"EMAIL" VARCHAR(254),"AVATAR_URL" VARCHAR(254),"HASHER" VARCHAR(254),"PASSWORD" VARCHAR(254),"SALT" VARCHAR(254),"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
create table "TOKENS" ("UUID" VARCHAR(254) NOT NULL,"EMAIL" VARCHAR(254) NOT NULL,"CREATION_TIME" TIMESTAMP NOT NULL,"EXPIRATION_TIME" TIMESTAMP NOT NULL,"IS_SIGN_UP" INTEGER,"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
create table "RATINGS" ("USER_ID" INTEGER NOT NULL,"TITLE_ID" INTEGER NOT NULL,"RATING_TYPE" VARCHAR(254) NOT NULL,"RATING" DOUBLE NOT NULL,"MODIFIED_TIME" TIMESTAMP NOT NULL,"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
create index "USER_TITLE_IDX" on "RATINGS" ("USER_ID","TITLE_ID");
create table "VIDEOS" ("TITLE_ID" INTEGER NOT NULL,"USER_ID" INTEGER NOT NULL,"VIDEO_ID" VARCHAR(254) NOT NULL,"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"MODIFIED_TIME" TIMESTAMP NOT NULL);
create index "TITLE_IDX" on "VIDEOS" ("USER_ID","TITLE_ID");
